import 'bootstrap/dist/css/bootstrap.min.css';
import '../index.css'

export default function About() {
    return (
        <section className='container-fluid container-xl'>
            <h1 className='ms-3 mt-3'>Hello!!</h1>
            <p className='ms-3 my-4'>Praesent hendrerit commodo ullamcorper. Pellentesque eget mi diam. Ut vehicula, risus vitae egestas fermentum, eros libero tempor risus, ut commodo eros tellus non ante. Curabitur eget ornare sapien. Ut blandit sem ac tellus semper finibus. Nullam velit libero, sagittis ut mi quis, ultricies molestie lorem. Nullam dictum vitae ligula ac porta. Nulla feugiat nisi diam, at pellentesque ipsum consectetur non. Sed id quam non arcu maximus sodales nec non lectus. Pellentesque quis lectus non mauris aliquet volutpat non et lorem. Maecenas elementum diam lorem, eu feugiat erat ultricies nec. In hac habitasse platea dictumst. Nulla blandit vitae nulla dapibus dignissim. Sed nec ante vel tortor interdum iaculis convallis et mi.</p>
            <p className='ms-3 my-4'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dignissim ipsum ipsum. Etiam in hendrerit velit. Integer ut metus in nisl ornare vestibulum id at dui. Maecenas dui ante, mattis at lacus sed, ullamcorper porta diam. Morbi sed quam pulvinar est molestie dapibus. Quisque id lacinia nisl. Aenean pharetra quis ligula id auctor. Vestibulum tempus ante id tellus lacinia, sodales tincidunt lectus lobortis. Donec mollis lorem nec metus facilisis, non fermentum nibh molestie. Mauris fermentum urna elementum viverra facilisis. Quisque eget turpis mollis, blandit elit eu, posuere nulla. Aliquam finibus sodales posuere. Aenean commodo iaculis purus a convallis.</p>
            <p className='ms-3 my-4'>Nam et urna nec tellus feugiat lobortis ac sit amet magna. In eu libero mollis, efficitur tortor eu, tempus dui. Integer auctor erat quis luctus condimentum. Donec feugiat nulla ut mauris pharetra, eget euismod metus maximus. In sed risus interdum turpis laoreet volutpat. Proin placerat erat et sapien mattis ornare. Proin mauris ligula, pharetra id semper sit amet, vehicula id nisi. Suspendisse consectetur lorem ut dui ullamcorper, dictum posuere eros suscipit. Aliquam erat volutpat. Praesent pellentesque, lacus quis commodo bibendum, velit turpis laoreet lectus, in malesuada dolor nisi sed ipsum. Suspendisse quam est, consectetur quis tortor sit amet, bibendum tempus velit. Etiam eu facilisis quam.</p>
            <p className='ms-3 my-4'>Donec ut nisl eu orci pellentesque consequat eget vel purus. Vestibulum mattis augue ac odio ultrices euismod. Morbi nec sem elementum, vestibulum sapien ut, volutpat felis. Mauris eget enim tincidunt, fermentum dolor dictum, ultrices nisl. Praesent tempor feugiat mauris, et luctus tortor interdum et. Cras placerat in elit sit amet ultrices. In eleifend dolor nec tellus aliquet porta. Nulla porta sem auctor tellus iaculis, eu varius nisi maximus.</p>
            <p className='ms-3 my-4'>Duis elementum blandit urna, in volutpat augue luctus at. Mauris congue, turpis ac maximus gravida, risus lectus consequat nisi, ultricies posuere metus tortor non diam. Integer sollicitudin tellus a orci elementum dictum. Phasellus sollicitudin, velit eu consequat laoreet, nibh eros sagittis arcu, nec porttitor est elit nec risus. Duis finibus lacus risus, auctor ultrices nunc congue vel. Etiam id dolor ut mauris aliquet tincidunt. Donec at laoreet mauris. Etiam maximus metus id nibh hendrerit suscipit. Sed rhoncus, lacus et elementum ultrices, mi nunc dapibus lorem, sit amet aliquet velit enim ut odio. Morbi lacinia orci non metus dictum, quis laoreet dui porttitor. Aenean dui urna, fermentum quis libero nec, sagittis pellentesque nulla. In pellentesque ipsum tempus mauris porttitor lobortis. Sed vitae suscipit nibh, ut rutrum mi. Nulla molestie efficitur dui, convallis aliquam ligula sodales et. In ornare turpis et dui interdum, vel congue massa molestie.</p>
            <p className='ms-3 my-4'>Praesent hendrerit commodo ullamcorper. Pellentesque eget mi diam. Ut vehicula, risus vitae egestas fermentum, eros libero tempor risus, ut commodo eros tellus non ante. Curabitur eget ornare sapien. Ut blandit sem ac tellus semper finibus. Nullam velit libero, sagittis ut mi quis, ultricies molestie lorem. Nullam dictum vitae ligula ac porta. Nulla feugiat nisi diam, at pellentesque ipsum consectetur non. Sed id quam non arcu maximus sodales nec non lectus. Pellentesque quis lectus non mauris aliquet volutpat non et lorem. Maecenas elementum diam lorem, eu feugiat erat ultricies nec. In hac habitasse platea dictumst. Nulla blandit vitae nulla dapibus dignissim. Sed nec ante vel tortor interdum iaculis convallis et mi.</p>
        </section>
    );
}