"""empty message

Revision ID: 07f6ed0bc3ea
Revises: 3efacc25b959
Create Date: 2024-08-27 19:30:06.712088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07f6ed0bc3ea'
down_revision = '3efacc25b959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
