"""empty message

Revision ID: e7c14f3dbf7a
Revises: 
Create Date: 2024-06-21 22:19:12.017419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c14f3dbf7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('pw', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('idx', name=op.f('pk_member')),
    sa.UniqueConstraint('email', name=op.f('uq_member_email'))
    )
    op.create_table('memo',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('pw', sa.String(length=30), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('postdate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('idx', name=op.f('pk_memo'))
    )
    op.create_table('post',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('photo', sa.String(length=500), nullable=True),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('postdate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('idx', name=op.f('pk_post'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('memo')
    op.drop_table('member')
    # ### end Alembic commands ###
